### ISSUE TITLE
Behaviour of `path_loader`  

### ISSUE THREAD

**Issue by barryrowlingson** [davidchall/jinjar#10]
I've used jinja a lot in Python projects so thought I'd try this package for R, but having some problems loading child templates with `include`:

I have a base template:
```
Include here.
{% include "me.tmpl" %}
```
and in the same folder the `me.tmpl` template:

```
This is me
```

From that location as working folder, rendering fails (as expected) because there's no loader specified to get the sub-template:

```
> render(fs::path("base.tmpl"))
Error: [inja.exception.render_error] (at 2:12) include 'me.tmpl' not found
```

Adding a `path_loader` with either `"/"`, `"."` or `""` (empty string) as the path results in a working include:

```
> confz = jinjar_config(loader=path_loader("/"))
> render(fs::path("base.tmpl"), .config=confz)
[1] "Include here.\nThis is me\n\n"
> confz = jinjar_config(loader=path_loader("."))
> render(fs::path("base.tmpl"), .config=confz)
[1] "Include here.\nThis is me\n\n"
> confz = jinjar_config(loader=path_loader(""))
> render(fs::path("base.tmpl"), .config=confz)
[1] "Include here.\nThis is me\n\n"
```

However, running from the parent folder, none of the above work (as expected) but I can't make anything work. Not the obvious relative path:
```
> confz = jinjar_config(loader=path_loader("./templates"))
> render(fs::path("templates/base.tmpl"), .config=confz)
Error: [inja.exception.file_error] failed accessing file at 'me.tmpl'
```
Note the slightly different error message to "include 'me.tmpl' not found" above.

Or even an absolute path:
```
> confz = jinjar_config(loader = path_loader(file.path(getwd(),"templates")))
> render(fs::path("templates/base.tmpl"), .config=confz)
Error: [inja.exception.file_error] failed accessing file at 'me.tmpl'
```
Although the path is correct and the template is there:
```
> confz
Path loader: /tmp/jinja/templates
Syntax: {% block %} {{ variable }} {# comment #}> 
> file.exists("/tmp/jinja/templates/me.tmpl")
[1] TRUE
```

So am I misunderstanding something about template loading here? What is the path relative to? The working directory, the parent template, or something else? Why does `"/"` work in the first instance? 

I think I might have to set my working directory to the top level folder I'm rendering to get any of this to work, but I don't want to have to wrap every `render` call in a `withr::with_dir` or similar. Am I missing something?

**Comment by davidchall** [comment]
Hi @barryrowlingson,

I've identified the issue and merged the fix. If you like, you can test it out using the development version:

```r
# install.packages("remotes")
remotes::install_github("davidchall/jinjar")
```

Since this is quite an important bug, I plan to release a patch version to CRAN soon.
