### ISSUE TITLE
How to pass length-1 vector as vector?

### ISSUE THREAD

**Issue by YStrauchP4** [davidchall/jinjar#27]
Hi!

R has this weird quirk that everything is a vector, even strings.

If my template uses a for loop on a vector, it succeeds if there's more than one entry but crashes if its length is just one, I guess some internal logic casts it to a string/number instead of an iterable with one element. This makes my templates crash randomly and I had to implement a helper function to manually cast vectors of length one to a list when I need to iterate over it. That's quite ugly...

I'm not sure if you can do anything about this, I guess you need to guess the data types and convert them for the C++ data types and you can't know if someone wants to iterate over a vector or use it as a string, but I thought I leave a ticket as this is an annoying caveat of R. Maybe add some documentation if you can't fix it haha

**Comment by YStrauchP4** [comment]
Thanks for your quick response!
Using the as-is operator is certainly less ugly than my helper function, wasn't aware of this operator and will certainly use it instead! Thanks for adding it to the docs!

**Comment by 33Vito** [comment]
Hi David, 

Just want to add that this will work with a list input - e.g. In my workflow, I use a YAML file to contain all the parameters required by the Jinja template. The YAML object loaded into R becomes a deeply nested list.

```r
render(template, !!!I(list(people = c("Andy")))) |> cat()

**Comment by davidchall** [comment]
Hi @33Vito - So in your use case, you want to specify that _all_ length-1 vectors should be treated as vectors. Is that right?

**Comment by davidchall** [comment]
Hi @33Vito - you can apply `I()` to every value in your deeply nested list using `purrr::modify_tree()`.

Here's an example, demonstrating that field1 and field3 are both treated as vectors.

``` r
library(jinjar)

# data stored in nested list (read from YAML)
data <- list(field1 = "value1", field2 = list(field3 = "value3"))

# wrap every value in I() to preserve vectors
data2 <- purrr::modify_tree(data, leaf = I)

# inspect data structures
str(data)
#> List of 2
#>  $ field1: chr "value1"
#>  $ field2:List of 1
#>   ..$ field3: chr "value3"
str(data2)
#> List of 2
#>  $ field1: 'AsIs' chr "value1"
#>  $ field2:List of 1
#>   ..$ field3: 'AsIs' chr "value3"

# render example template
template <- "
{% for val in field1 %}{{ val }}{% endfor %}
{% for val in field2.field3 %}{{ val }}{% endfor %}
"

render(template, !!!data2)
#> [1] "\nvalue1\nvalue3\n"
```

<sup>Created on 2023-03-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by 33Vito** [comment]
> 

This is awesome. Thanks, mate.
